[package]
name = "aegis-fuzzlite"
version = "1.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aegis-format = { path = "../aegis-format" }
aegis-core = { path = "../aegis-core" }

